# src/main/resources/application.yml

server:
  port: 8080

jwt:
  secret: Ov/GqLXAIjioM7ihi3YkP3ZNFdtqYXNfGN79WpQLqMs=
  expiration: 3600000  # 1 hour (ms)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password:
