# src/main/resources/application.yml

server:
  port: 8080

spring:
  application:
    name: buyhouse

  datasource:
    url: jdbc:mysql://localhost:3306/train_movie?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  secret: Ov/GqLXAIjioM7ihi3YkP3ZNFdtqYXNfGN79WpQLqMs=
  expiration: 3600000  # 1 hour (ms)

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace
